### ISSUE TITLE
Google App Engine RemoteApiProxy error

### ISSUE THREAD

**Issue by eurobob** [tomwalder/php-gds-session#4]
I get this error when enabling the session handler. What's going on?

`Fatal error: Uncaught exception 'google\appengine\runtime\ApplicationError' with message 'Illegal string "dev~None" in dataset id.' in /Users/rob/google-cloud-sdk/platform/google_appengine/php/sdk/google/appengine/runtime/RemoteApiProxy.php:84 Stack trace: #0 /Users/rob/google-cloud-sdk/platform/google_appengine/php/sdk/google/appengine/runtime/ApiProxy.php(40): google\appengine\runtime\RemoteApiProxy->makeSyncCall('datastore_v4', 'Lookup', Object(google\appengine\datastore\v4\LookupRequest), Object(google\appengine\datastore\v4\LookupResponse), 60) #1 /Users/rob/web/projects/_legacy/writerhythm/wordpress/vendor/tomwalder/php-gds/src/GDS/Gateway/ProtoBuf.php(220): google\appengine\runtime\ApiProxy::makeSyncCall('datastore_v4', 'Lookup', Object(google\appengine\datastore\v4\LookupRequest), Object(google\appengine\datastore\v4\LookupResponse), 60) #2 /Users/rob/web/projects/_legacy/writerhythm/wordpress/vendor/tomwalder/php-gds/src/GDS/Gateway/ProtoBuf.php(253): GDS\Gateway\ProtoBuf->execute('Lookup', Object(google\appengin in /Users/rob/google-cloud-sdk/platform/google_appengine/php/sdk/google/appengine/runtime/RemoteApiProxy.php on line 84`

**Comment by eurobob** [comment]
So I took a gamble and deployed the change, and it works on the live app.

What's wrong on local that means it doesn't work?
